### ISSUE TITLE
read write user access codes

### ISSUE THREAD

**Issue by Miguel-DL** [uhppoted/node-red-contrib-uhppoted#13]
I would like to be able to assign opening codes and delete them, it seems I can only read/write cards.
could someone tell me how to do it or even develop it?
thank you very much.

**Comment by uhppoted** [comment]
Closing - insufficient information.

**Comment by Miguel-DL** [comment]
Hello again, sorry for taking so long to reply, basically I want to replace the card readers with numeric keypads. Which brings me to instead of authorizing cards I need to authorize codes on a given schedule.
For example to create the user josé with the code 2341 so that it opens in certain hours and not in others.
Just being able to read and write users and codes in the nodes would be enough.

**Comment by uhppoted** [comment]
No worries - I thought you had probably just figured it out and forgotten to close the issue :-). I assume you want to use something like this?

- [UHPPOTE Touch Access Control Keypad with Wiegand 26-bit Interface](https://www.amazon.com/UHPPOTE-Wiegand-Access-Control-Keypad/dp/B01N6JBMU3)

_(if not can you please include the details of the controller + keypad you are intending to use)_

I don't have one of those so am going to have to go by the comments on the Amazon page - it looks like you simply treat the access codes as card numbers. The UHPPOTE controller requires 26-bit Wiegand codes and typically those come from cards or key fobs but as long as it's a 26-bit Wiegand interface it's happy and the keypad seems to present access codes the same way.

If you're using [node-red-contrib-uhppoted](https://github.com/uhppoted/node-red-contrib-uhppoted) then the relevant nodes are:
- `uhppoted-put‑card` (sets the basic access for a card number - or access code in your case)
- `uhppoted-set-time-profile` (allows you to schedule access)

There's more detail in the NodeRED node documentation (accessible from within the IDE) but if you want a quick summary the CLI documents them in some detail:
- [put-card](https://github.com/uhppoted/uhppote-cli#put-card)
- [set-time-profile](https://github.com/uhppoted/uhppote-cli#set-time-profile)

At the moment _node-red-contrib-uhppoted_ doesn't support access+PIN - if you need it let me know and I'm happy to add the functionality.

**Comment by uhppoted** [comment]
As suggestion - it might be a good idea to start with a basic sanity check. Download the [CLI](https://github.com/uhppoted/uhppote-cli) (there are prebuilt executables for Windows, MacOS, Linux and Raspberry Pi on the [releases](https://github.com/uhppoted/uhppote-cli/releases) page) and start with the following commands:

_Basic communications check:_
```
uhppote-cli --debug get-devices
```
You should get output along these lines:
> uhppote-cli --debug get-devices
> ... using default configuration from /usr/local/etc/com.github.uhppoted/uhppoted.conf
> ... request
>  ...          00000000  17 94 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
>  ...          00000010  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
>  ...          00000020  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
>  ...          00000030  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
>  ...          
>  ... sent 64 bytes to 192.168.1.255:60000
>  ... received 64 bytes from 192.168.1.100:60000
>  ...          00000000  17 94 00 00 41 78 1e 12  c0 a8 01 64 ff ff ff 00  |....Ax.....d....|
>  ...          00000010  c0 a8 01 01 52 fd fc 07  21 82 08 92 20 19 08 15  |....R...!... ...|
>  ...          00000020  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
>  ...          00000030  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
>  ...          
> Alpha  405419896  192.168.1.100  255.255.255.0  192.168.1.1  00:12:23:34:45:56  v8.92  2018-11-05

_Controller communications check_
```
uhppote-cli --debug get-device <controller serial number>
```

_Controller status_
```
uhppote-cli --debug get-status <controller serial number>
```
> uhppote-cli --debug get-status 405419896
> 
>  ... using default configuration from /usr/local/etc/com.github.uhppoted/uhppoted.conf
>  ... sent 64 bytes to 192.168.1.100:60000
> 
>  ... request
>  ...          00000000  17 20 00 00 78 37 2a 18  00 00 00 00 00 00 00 00  |. ..x7*.........|
>  ...          00000010  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
>  ...          00000020  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
>  ...          00000030  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
>  ...          
> 
>  ... received 64 bytes from 192.168.1.100:60000
>  ... response
>  ...          00000000  17 20 00 00 78 37 2a 18  45 00 00 00 02 01 01 01  |. ..x7*.E.......|
>  ...          00000010  a1 98 7c 00 20 21 08 10  10 28 32 2c 00 00 00 00  |..|. !...(2,....|
>  ...          00000020  00 00 00 00 00 09 32 24  00 00 00 00 00 00 00 00  |......2$........|
>  ...          00000030  00 00 00 22 11 08 00 00  00 00 00 00 00 00 00 00  |..."............|
>  ...          
> 405419896  false false false false false false false false 0    2022-11-08 09:32:24 0          0 00 00 | 69    2   true  1 1     8165537    2021-08-10 10:28:32 44

The _get-status_ command displays the most recent event so if you have entered an access code on the keypad you should see an access granted/denied event along with the details of the number entered.

**Comment by uhppoted** [comment]
Oh no! That's sad! A couple other people have mentioned that they've had trouble getting off-brand card readers to work but mostly it doesn't seem to be a problem. Can you let me know which particular reader it is? I'll put on the _incompatible hardware_ list so that at least other people will be aware.

BTW, I've added card+PIN to the TODO list - not sure if it will make it into the current dev cycle but will try my best.

**Comment by uhppoted** [comment]
Closing - feel free to reopen it if you need to
