### ISSUE TITLE
listen node Problem

### ISSUE THREAD

**Issue by savage7** [uhppoted/node-red-contrib-uhppoted#3]
I can't get the "listen" node to work, it doesn't receive any events.

**This mqtt setup works:**
I've a working mqtt Env:
UT0311-L0x.223195309.address = 192.168.1.123:60000
UT0311-L0x.223195309.door.1 = Front Door
UT0311-L0x.223195309.door.2 = Side Door

the listener is set to 192.168.1.131:60001 
When I open the door, I get an event.

**Node red setup:**
it runs on the same "machine"/docker.
the listener is set to 192.168.1.131:60002
I choose another port, so that there is no port collision. I also tried it with 60001.
**When I open the door, I dont receive an event via the listen node.**

I looked at your example. All the other "api" node like get-listener, set-listener work, get-status...
i.e i did set the listener via node.

my door config:
<img width="478" alt="Bildschirmfoto 2020-12-10 um 21 32 45" src="https://user-images.githubusercontent.com/971353/101826443-490ca800-3b2f-11eb-80ef-135d9a213967.png">

Do a have an error in the config?
I dont get an "error" trace in the debug console, like "cannot bind adress". The listen node also doesnt show an "red error" below the node.
Can I provide some debug output somehow (the controller config is set to debug)?

thxs alot for your help!!!

**Comment by uhppoted** [comment]
Hi,

If I've understood it correctly:
- 223195309 is your real controller
- _uhppoted-mqtt_ is running on a Docker instance, listening for events on port 60001
- _node-red_ is running on the same Docker instance as _uhppoted-mqtt_, listening for events on port 60002

Is that correct?

The first step in debugging this is to confirm that the events are getting sent to where you expect them:
1. Can you confirm (using Wireshark or tcpdump or the _uhppote-cli_ `listen` command) that you are receiving events on port 60002 on the machine that is hosting the Docker instance ? (if you're using _uhppote-cli_ you'll have to do it without the Docker instance running)
2. Can you confirm (using Wireshark or tcpdump or the _uhppote-cli_ `listen` command) that you are receiving events on port 60002 on the Docker instance ?

**Comment by uhppoted** [comment]
Hi,

Quick addendum - if you are running NodeRED in a Docker container, have you forwarded UDP port 60002?

```
docker run -it -p 1880:1880 -p 60002:60002/udp --name uhppoted nodered/node-red
```

You may also need to set your listen address to:
```
0.0.0.0:60002
```
which is the simplest way of making sure the container is _listen_ service is bound to the internal container network address.

**Comment by savage7** [comment]
Nodered runs in host network mode, but I tried adding the ports:
-p 60002:60002/udp
Also tried to add tcp too...
--> no difference

I changed the listen address to: 
0.0.0.0:60002
--> no difference

Tcpdump:
tcpdump -i any -nn | grep 192.168.1.123
Controller ip is: 192.168.1.123
Docker machine ip: 192.168.1.131
Listener Port: 60002

outside docker on the host machine:
16:49:20.931568 IP 192.168.1.123.60000 > 192.168.1.131.60002: UDP, length 64

Inside the docker container:
17:59:00.330065 IP 192.168.1.123.60000 > 192.168.1.131.60002: UDP, length 64

For me the traces look ok still, the "listen" node doesnt output anything. :( 
I did setup a nodered instance on my local machine, not within docker. same I dont get any events :(

**Comment by uhppoted** [comment]
Hmm ... there may be a problem with Docker receiving UDP multicast packets in host networking mode (https://groups.google.com/g/node-red/c/g5ZSzr7iNI8) but I'm going to have to dig into it to figure if that's actually the case. 

Unfortunately host networking mode doesn't work on a Mac and I don't have a RaspberryPi to hand so it's going to take a little time to get set up. Some things to try while I do that:

1. Try a "normal" container with bridged networking (this worked out of the box for me):
```
docker run -it -p 1880:1880 -p 60001:60001/udp --name uhppoted nodered/node-red
```

2. Try `uhppote-cli --debug listen`

Can you also please post your Dockerfile and the command you use to run it.

**Comment by savage7** [comment]
Ok I simplified my setup, to remove any error regarding docker.
I created a local node-red installation on my mac (192.168.1.109).

1. uhppote-cli --debug listen
Works, I get the events.

2. Add the listen node and configured it
- quit uhppote-cli
--> No events received, I get no message from the listen node.
I used this configuration on my mac:
<img width="490" alt="Bildschirmfoto 2020-12-13 um 20 16 56" src="https://user-images.githubusercontent.com/971353/102021519-96338880-3d80-11eb-834b-beaa479ddf98.png">

I honestly don't know whats wrong.

**Comment by uhppoted** [comment]
Have to admit I'm fairly baffled as well - there are definitely networking complexities around docker, IPv4/IPv6 and the more recent Linux releases and I'm still digging into those. 

But .. I was able to get _node-red_ receiving events from my local development controller on a remote _(vultr)_ Ubuntu 20.10 VPS  without doing anything at all special.  These were the steps I followed:

1. Configure firewall and startup scripts so allow TCP port 1880 and UDP port 60001 from my development system public IP
2. Start Ubuntu 20.10 instance
3. Login via `ssh`
4. `apt-get update`
5. `apt-get install npm`
6. `npm install -g --unsafe-perm node-red`
7. ` node-red`
8. Open the VPS _node-red_ page in a browser
8. Install `node-red-contrib-uhppoted` to the palette
9. Create a flow with a `listen` node connected to `debug` node (with the `listen` address configured as `0.0.0.0:60001`)

On my development system:
1. `./bin/uhppote-cli --debug set-listener <serial#> <VPS address>:60001`
2. Swipe card

The _swipe_ event appears in the debug pane of the node-red page. You could try this just to establish a baseline working system as starting point for further debugging - or if you can let me have your public IP address am happy to temporarily set up a system that you can access.

One other thing:

`uhppote-cli` is the original application and I remember struggling to get it to work correctly with both WiFi and LAN enabled on my Mac, as a result of which it has a somewhat more complex default address detection algorithm i.e. there's a possibility `uhppote-cli --debug listen` may not be binding to 192.168.1.109. 

Some more things to try:

1. `uhppote-cli --debug listen` and use `netstat` or `lsof` to see what address:port it is bound to
2. `uhppote-cli --listen 192.168.1.109:60001 --debug listen`, to explicity bind to the same listen address:port as _node-red_
3. Disable WiFi entirely and see if that allows node-red to receive events

**Comment by uhppoted** [comment]
Hi,

Having experimented some more with a Ubuntu 20.10 VPS I'm able to receive events using _NodeRED_ in a _docker_ container in both _host networking mode_ and _normal networking mode_ without doing anything special. 

The only setting that seemed critical was that _listen_ address in the the _config_ node, which must be set to **`0.0.0.0:60001`**.

The command lines used to start NodeRED in a docker container were:

- interactive, host network mode:
```
docker run --interactive --net=host nodered/node-red
```
- detached, host network mode:
```
docker run --detach --net=host nodered/node-red
```
- interactive, docker proxy (normal):
```
docker run --interactive --publish 1880:1880 --publish 60001:60001/udp nodered/node-red
```
- detached, docker proxy (normal):
```
docker run --detach --publish 1880:1880 --publish 60001:60001/udp nodered/node-red
```

**Comment by uhppoted** [comment]
Almost forgot - if you're expecting to receive _door relay_ and _push button_ events, then please be aware of [Door open or closed event not generated](https://github.com/uhppoted/uhppote-core/issues/2).

The CLI has an update that allows you to enable door and push button event recording.

**Comment by uhppoted** [comment]
Hi,

I'm going to close this issue - NodeRED flows on Ubuntu (both in and outside of Docker containers) were able to receive events without a problem in all configurations I tried. The only critical points to note were:

1. The firewall should be configured to allow UDP events on the `listen` port e.g.:
    ```
    ufw allow from <address> to any port 60000 proto udp
    ```
    
2. _door open_, _door close_  and _door button_ events are only generated if enabled via `record-special-events`. Support for this function has been added in v0.6.7.

3. The `listen` address in the `config` should be '0.0.0.0:<port>'

Please feel free to reopen if/when you have any more information to add.

**Comment by savage7** [comment]
I'll try 0.6.7 again. 
Yes sure, I've tried all variants you described but was not able to listen to message from the controller. 

Thanks alot for your help and your great work! :)

**Comment by uhppoted** [comment]
Hmm, I don't think 0.6.7 will make any difference - it only really adds the `record-special-events` node. 

I'm really puzzled because this 'just works' for me - can you maybe upload some Wireshark captures? Maybe I can figure out something from the actual messages..

**Comment by savage7** [comment]
I traced it on my mac not in docker.

Mac ip: 192.168.1.142
Controller id: 192.168.1.123
Capture filter applied:
ip.src == 192.168.1.123

I opened the web interface on my mac and opened the door --> thats the tcp, http pakets 
Then the controller sends a udp message to the Mac.

Trace:
[trace.pcapng.zip](https://github.com/uhppoted/node-red-contrib-uhppoted/files/5763880/trace.pcapng.zip)

Configuration:
<img width="494" alt="Bildschirmfoto 2021-01-04 um 10 11 16" src="https://user-images.githubusercontent.com/971353/103519123-41fa6080-4e75-11eb-84b3-e416d1e3d8c6.png">

**Comment by uhppoted** [comment]
Thanks! That made it easy - the message bytes are:
```
   0000   19 20 00 00 ad b0 4d 0d 35 03 00 00 02 01 01 01
   0010   8e 01 a8 c0 20 21 01 04 11 07 08 2c 01 01 00 00
   0020   00 00 00 00 00 11 07 08 00 00 00 00 00 00 00 00
   0030   00 01 00 21 01 04 00 00 00 00 00 00 00 00 00 00
```

Normally messages start with a `0x17` and that's what the NodeRED codec expects. However, I have seen this before on an older controller and there is a [patch](https://github.com/uhppoted/uhppote-core/blob/031c7188aca83967954931770dd6f955f3416636/encoding/UTO311-L0x/UT0311-L0x.go#L201-L204) for it in the Go code:

	// PATCH: accommodates undocumented but seemingly valid 'listen' events that start with 0x19
	if (bytes[0] != 0x17) && (bytes[0] != 0x19 || bytes[1] != 0x20) {
	    return errors.New(fmt.Sprintf("Invalid start of message - expected 0x17, received 0x%02x", bytes[0]))
	}

Which I had forgotten about and missed when doing the port to NodeRED :-(. Apologies .. I should have a fix out in the next day or so.

Out of curiosity - what version is the firmware on your controller?

**Comment by savage7** [comment]
Oh that is great 😊  thank you!

I don't see a "firmware version" but a "driver version" in the web interface, that is: V6.62.51215

**Comment by uhppoted** [comment]
Yup, v6.62 was the firmware version on the controller that patch was made for - suspect it was something that got overlooked when they were updating the protocol because it was fixed in later versions. 

I'll make a note of it in the README.

**Comment by uhppoted** [comment]
Hi,

I've pushed and update to the `node-red-contrib-uhppoted` repo to handle the v6.62 events and also updated the implementation in `uhppote-core` and `uhppote-simulator`.

I'm going to hold off on releasing it for a couple of days though, in the hope that _NodeRED_ will release an update for a [security issue](https://github.com/node-red/node-red-admin/pull/12) in one of their dependencies.

If you want to try out the fix, please use the version in the `master` branch - otherwise I'll publish a new version early next week.

**Comment by savage7** [comment]
Sure just take your time, I'll wait for the deployment.

**Comment by uhppoted** [comment]
Hi,

I've release v0.6.8 with the fix for the _listen events_ and published it to _NPM_ and _NodeRED_. 

Can you give it a try and see if you now receive events?

**Comment by savage7** [comment]
@uhppoted 
Yes it works :heart:
This is really cool, the node red integration is so clean and nicely done :)  
Thanks alot.

**Comment by uhppoted** [comment]
Oh, that's *great*! Thanks for trying it out .. and thanks for your patience while we got to the bottom of the problem!

Am very glad you're finding the node red integration straightforward - I feel like it just opens up a world of possibilities :-).
