### ISSUE TITLE
Config Node

### ISSUE THREAD

**Issue by neyStyle** [uhppoted/node-red-contrib-uhppoted#5]
Hello,

i dont can find my Access Controller.
I reach them by typing: 10.3.1.65 in Browser.
But in the Config Node i don´t can find him.

What i make wrong.

`[{"id":"a640a000.d83cb","type":"tab","label":"1-get-devices","disabled":false,"info":"# get-devices: basic example\n\nIssues a _get-devices_ broadcast command and displays the received information for the access controller with serial number 405419896.\n\nThe _get-devices_ flow in the _dashboard_ flowset contains a more complete example."},{"id":"6a470566.d4725c","type":"get-devices","z":"a640a000.d83cb","name":"get-devices","topic":"get-devices","config":"cbd92359.dbf19","x":290,"y":100,"wires":[["31429769.0664e8","6699677.c355098","cc21d868.6db82"]]},{"id":"31429769.0664e8","type":"debug","z":"a640a000.d83cb","name":"received","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":520,"y":60,"wires":[]},{"id":"82a8517a.6ef88","type":"inject","z":"a640a000.d83cb","name":"test","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"test-get-controllers","payload":"{}","payloadType":"json","x":130,"y":100,"wires":[["6a470566.d4725c","67f4c57c.2f9e94"]]},{"id":"6699677.c355098","type":"function","z":"a640a000.d83cb","name":"parse","func":"for (i=0; i<msg.payload.length; i++) {\n    deviceId = msg.payload[i].deviceId\n    device = msg.payload[i].device;\n    if (deviceId == 423133278) {\n        return msg.payload[i];        \n    }\n}\n\nreturn { device: {} }","outputs":1,"noerr":0,"initialize":"","finalize":"","x":510,"y":100,"wires":[["86fc5747.ceaf78","27be4ab8.2eac96","301b11ef.dbf73e","10c3ab90.e85124","5707c80e.570f78","86dd1102.ee59d","c6be71d1.b0f19"]]},{"id":"86fc5747.ceaf78","type":"debug","z":"a640a000.d83cb","name":"serial-number","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"device.serialNumber","targetType":"msg","statusVal":"","statusType":"auto","x":720,"y":100,"wires":[]},{"id":"27be4ab8.2eac96","type":"debug","z":"a640a000.d83cb","name":"address","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"device.address","targetType":"msg","statusVal":"","statusType":"auto","x":700,"y":140,"wires":[]},{"id":"301b11ef.dbf73e","type":"debug","z":"a640a000.d83cb","name":"netmask","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"device.netmask","targetType":"msg","statusVal":"","statusType":"auto","x":700,"y":180,"wires":[]},{"id":"10c3ab90.e85124","type":"debug","z":"a640a000.d83cb","name":"gateway","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"device.gateway","targetType":"msg","statusVal":"","statusType":"auto","x":700,"y":220,"wires":[]},{"id":"5707c80e.570f78","type":"debug","z":"a640a000.d83cb","name":"MAC","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"device.MAC","targetType":"msg","statusVal":"","statusType":"auto","x":690,"y":260,"wires":[]},{"id":"86dd1102.ee59d","type":"debug","z":"a640a000.d83cb","name":"version","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"device.version","targetType":"msg","statusVal":"","statusType":"auto","x":700,"y":300,"wires":[]},{"id":"c6be71d1.b0f19","type":"debug","z":"a640a000.d83cb","name":"date","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"device.date","targetType":"msg","statusVal":"","statusType":"auto","x":690,"y":340,"wires":[]},{"id":"cc21d868.6db82","type":"debug","z":"a640a000.d83cb","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":510,"y":160,"wires":[]},{"id":"67f4c57c.2f9e94","type":"get-device","z":"a640a000.d83cb","name":"","topic":"","config":"cbd92359.dbf19","x":290,"y":180,"wires":[["cc21d868.6db82"]]},{"id":"cbd92359.dbf19","type":"config","name":"examples","timeout":"5000","bind":"10.3.1.65","broadcast":"10.3.1.65:60000","listen":"10.3.1.65:60001","controllers":"{\"423133278\":{\"address\":\"10.3.1.65:60000\",\"broadcast\":true}}","debug":true}]`

**Comment by uhppoted** [comment]
Hi,

You have the _bind_, _broadcast_ and _listen_ addresses set to the IP address of the controller - they should be set to the IP address of the host machine. In general you can normally just use:

- `0.0.0.0` for the _bind_ address
- `255.255.255.255:60000` for the _broadcast_ address 
- `0.0.0.0:60001` for the _listen_ address

If you get an `"uhppoted::Error: send EACCES 255.255.255.255:60000` error you'll need to set them to the address of your LAN interface which you can get using `ifconfig` (`ipconfig` on Windows) e.g.
```
> ifconfig

...
en3: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=50b<RXCSUM,TXCSUM,VLAN_HWTAGGING,AV,CHANNEL_IO>
	ether 0c:4d:e9:cd:ac:ea 
	inet6 fe80::1084:26d8:eeb8:5cd5%en3 prefixlen 64 secured scopeid 0x4 
	inet 192.168.1.100 netmask 0xffffff00 broadcast 192.168.1.255
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect (1000baseT <full-duplex,flow-control>)
	status: active
...
```
which gives me a _bind_ and _listen_ address of 192.168.1.100 and a _broadcast_ address of 192.168.1.255:

```
...
inet 192.168.1.100 netmask 0xffffff00 broadcast 192.168.1.255
...
```

**Comment by neyStyle** [comment]
Hey Perfect,
it works very fine.

one Last Question i have. 
On the Webpage i can gave the RFID-Codes Names, it is possible to become this names out of the Controller.
I Mean when i listen an Event comes with the Name.

Here is a example, i hope you understand it, see after card is the Name.....

`
{"deviceId":423133278,"event":{"index":105719,"type":{"code":1,"event":"card swipe"},"granted":true,"door":2,"direction":{"code":1,"direction":"in"},"card":14341977,"Name":John,"timestamp":"2021-03-14 11:14:04","reason":{"code":1,"reason":"swipe"}}}
`

**Comment by uhppoted** [comment]
Oh great, very happy to hear that!

re. names. The names associated with a card are not stored on the controller so to add a name to an event you have to look it up in an external source (e.g. a MySQL database). I've attached an example [flow](https://github.com/uhppoted/node-red-contrib-uhppoted/files/6137358/flows.zip) that looks up the name in an internal _Javascript_ `Map` object and adds the name to the event. The `Map` is initialised in the `Setup` section of the function node and stored in a _NodeRED_ global variable.

To do this properly the names would be stored in e.g. a SQLite or MySQL database but setting something like that up is a bit beyond the scope of this project.
