### ISSUE TITLE
Relay Event Notification

### ISSUE THREAD

**Issue by TestUser0000000001** [uhppoted/node-red-contrib-uhppoted#6]
When the relay gets activated the listener sees the event and shows the door as "OPEN" > or true, when the relay closes itself 3 seconds later (or whatever the timer was set to) the CLOSED event is not fired to the listener.

All other events and features seem to be working.

**Comment by uhppoted** [comment]
Hi,

You may need to enable events for the door input contacts using the `record-special-events` node. 

The default controller configuration as shipped by the manufacturer only seems to generate access related events (e.g. _swipe_) and the other inputs need to be specifically enabled.

Sample trace - the _door open event_ has an `event.card` value of `8` and the _door closed event_ an `event.card` value of `9`.

```
DOOR OPEN:
{
  "deviceId": 405419896,
  "state": {
    "serialNumber": 405419896,
    "event": {
      "index": 333,
      "type": {
        "code": 2,
        "event": "door"
      },
      "granted": false,
      "door": 4,
      "direction": {
        "code": 1,
        "direction": "in"
      },
      "card": 8,
      "timestamp": "2021-03-16 11:07:28",
      "reason": {
        "code": 23,
        "reason": "door opened"
      }
    },
    "doors": {
      "1": true,
      "2": true,
      "3": true,
      "4": true
    },
    "buttons": {
      "1": false,
      "2": false,
      "3": false,
      "4": false
    },
    "system": {
      "status": 0,
      "date": "2021-03-16",
      "time": "11:07:28"
    },
    "specialInfo": 0,
    "relays": {
      "state": 0,
      "relays": {
        "1": false,
        "2": false,
        "3": false,
        "4": false
      }
    },
    "inputs": {
      "state": 0,
      "forceLock": false,
      "fireAlarm": false
    }
  }
}
```
```
DOOR CLOSED:
{
  "deviceId": 405419896,
  "state": {
    "serialNumber": 405419896,
    "event": {
      "index": 332,
      "type": {
        "code": 2,
        "event": "door"
      },
      "granted": false,
      "door": 4,
      "direction": {
        "code": 1,
        "direction": "in"
      },
      "card": 9,
      "timestamp": "2021-03-16 11:07:26",
      "reason": {
        "code": 24,
        "reason": "door closed"
      }
    },
    "doors": {
      "1": true,
      "2": true,
      "3": true,
      "4": false
    },
    "buttons": {
      "1": false,
      "2": false,
      "3": false,
      "4": false
    },
    "system": {
      "status": 0,
      "date": "2021-03-16",
      "time": "11:07:26"
    },
    "specialInfo": 0,
    "relays": {
      "state": 0,
      "relays": {
        "1": false,
        "2": false,
        "3": false,
        "4": false
      }
    },
    "inputs": {
      "state": 0,
      "forceLock": false,
      "fireAlarm": false
    }
  }
}
```

**Comment by TestUser0000000001** [comment]
Thanks for the quick reply, you say enable events. I just got into this project so Im not sure how to "enable".
I have used the record-special-events node already.
It shows the door sensor open/closed events but not the relay state events.
Also does not show push button ok status > only shows when pressed but not when released.
If there is already a writeup how to do this please point me to the correct section.

(record-special-events)
deviceId: 422244351
enable: true
updated: true

**Comment by uhppoted** [comment]
Oh, ok, I understand what you were asking now. The controller doesn't seem to generate events for the state of the door activation relays or push button release. At a guess it was a design decision made on the basis that those are essentially internal state for the controller. 

As a workaround you can poll the controller using `get-status` (e.g. after a relay open or push button press event) until you detect the change of state.

**Comment by TestUser0000000001** [comment]
Ok thanks for checking up on that. If it cant be done then ill make a work around.
Also can you provide some info on what module to use for the webui portion of the examples? Im just getting error components. Maybe make it more clear somewhere.

**Comment by uhppoted** [comment]
Added the additional components needed for the dashboard example flow to the [README](https://github.com/uhppoted/node-red-contrib-uhppoted#examples):

- [node-red-node-ui-list](https://flows.nodered.org/node/node-red-node-ui-list)
- [node-red-node-ui-table](https://flows.nodered.org/node/node-red-node-ui-table)
